<?php
namespace Services\HelloWorld;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface HelloWorldIf
{
    /**
     * @param string $name
     * @param string $key
     * @return string
     */
    public function sayHello($name, $key);
    /**
     * @param string $name
     * @return string
     */
    public function sayWorld($name);
}
